name: EC2 Docker Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    name: Clean up Docker on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and clean up Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "--- 1. Stopping Docker ---"
            sudo systemctl stop docker.socket
            sudo systemctl stop docker
            echo "--- 2. Deleting Docker data directory ---"
            sudo rm -rf /var/lib/docker
            echo "--- 3. Restarting Docker ---"
            sudo systemctl daemon-reload
            sudo systemctl start docker
            echo "--- 4. Checking disk usage ---"
            df -h
