name: Deploy AI Commander to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy and execute on EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "deploy.sh,requirements.txt,live_trader.py,universe_manager.py,dl_predictor.py,config/.env,data/v2_lightgbm_model.joblib" # 실행에 필수적인 파일만 전송
          target: "/home/ec2-user/upbit_auto_bot"

      - name: Run deployment script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/upbit_auto_bot
            chmod +x deploy.sh
            ./deploy.sh