name: Deploy and Run on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy and execute on EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "deploy.sh,requirements.txt,sentinel.py,universe_manager.py,dl_predictor.py,multi_asset_backtester.py,rl_environment.py,foundational_model_trainer.py,preprocessor.py,risk_manager.py,strategies/" # 필요한 모든 파일 전송
          target: "/home/ec2-user/upbit_auto_bot"

      - name: Run deployment script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/upbit_auto_bot
            chmod +x deploy.sh
            ./deploy.sh
